DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id              INTEGER PRIMARY KEY AUTO_INCREMENT,
	name            VARCHAR(255) NOT NULL,
	token           VARCHAR(255) NOT NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO users (name, token) VALUES ("tatsuya", "12345678910");
INSERT INTO users (name, token) VALUES ("toru", "12345678910");
INSERT INTO users (name, token) VALUES ("satoshi", "12345678910");
