DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id              INTEGER PRIMARY KEY AUTO_INCREMENT,
	name            VARCHAR(255) NOT NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
