version: '3'
services: 
#     api:
#         container_name: game-api
#         build:
#             context: ./api
#             dockerfile: Dockerfile
#         depends_on: 
#             - db
#         restart: unless-stopped
#         environment: 
#             API_SECRET: sample_api_secret
#         ports: 
#             - 8080:80
#         networks: 
#             - game-api
    db:
        image: mysql:latest
        container_name: game_db
        environment: 
            MYSQL_ROOT_HOST: db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: game_db
            MYSQL_USER: game
            MYSQL_PASSWORD: game
        ports: 
            - 3306:3306
        restart: unless-stopped
        volumes: 
            - ./data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        networks: 
            - game-api

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: game
            PMA_PASSWORD: game
            PMA_PORT: 3306
        ports:
            - 9090:80
        restart: always
        networks:
            - game-api

networks: 
    game-api: