version: '3'
services: 
    api:
        container_name: game-api
        build:
            context: ../build
        depends_on: 
            - db
        restart: unless-stopped
        ports: 
            - 8080:8080
        networks: 
            - game-api
        volumes: 
            - ..:/ca-tech-dojo
        command: "go run /ca-tech-dojo/cmd/game-api/server.go"

    db:
        image: mysql:latest
        container_name: game-db
        environment: 
            MYSQL_ROOT_HOST: db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: game-db
            MYSQL_USER: game
            MYSQL_PASSWORD: game
        ports: 
            - 3306:3306
        restart: unless-stopped
        volumes: 
            - ./data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        networks: 
            - game-api

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: game-phpmyadmin
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: game
            PMA_PASSWORD: game
            PMA_PORT: 3306
        ports:
            - 9090:80
        restart: always
        networks:
            - game-api

networks: 
    game-api: